name: newsstepsafefuture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # Add this line
    sdk: flutter
  intl: ^0.19.0  # Recommended for localization
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  another_flutter_splash_screen: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  onboarding: ^4.0.2
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  salomon_bottom_bar: ^3.3.2
  animated_bottom_navigation_bar: ^1.3.3
  dot_curved_bottom_nav: ^0.0.2
  flutter_widget_from_html_core: ^0.15.2
  youtube_player_flutter: ^9.1.0
  flutter_pdfview: ^1.4.0
  url_launcher: ^6.3.1
  flutter_web_browser: ^0.17.2
  flutter_html: ^3.0.0-beta.2
  provider: ^6.1.2
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.5
  html: ^0.15.4
  html_unescape: ^2.0.0
  flutter_translate: ^4.1.0
  translator: ^1.0.3+1
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^29.1.38
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/pdf/
    - assets/images/logo.png